services:
  mongo:
    image: mongo:latest
    container_name: biblio-backend
    restart: always
    environment:
      DB_NAME: bibliodb
      MONGO_INITDB_DATABASE: bibliodb
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db 
      - ./.docker/biblio-backend/seed.js:/docker-entrypoint-initdb.d/seed.js
  app:
    build: .
    container_name: biblio-frontend
    ports:
      - 3000:3000
    environment:
      MONGO_URI: mongodb://mongo:27017/bibliodb
    depends_on:
      - mongo